In [1]:
x = 2
y = 3

In [2]:
print(x,y)

2 3


In [3]:
print([x,y])

[2, 3]


In [4]:
print([x, y , 'a thing', 3, 2])

[2, 3, 'a thing', 3, 2]


In [5]:
s = "here is a string"

In [6]:
s.format()

'here is a string'

In [7]:
s = "here is a string with a first {} and there comes another {}"

In [8]:
s.format('argument', 4)

'here is a string with a first argument and there comes another 4'

In [9]:
import numpy as np

In [10]:
values = np.array([0 , 1, 2 , 3 , 1 , 0])

In [11]:
values.max()

3

In [12]:
values.argmax()

3

In [13]:
values[values.argmax()] == values.max()

True

In [15]:
values2 = np.array([[0 , 1, 2 , 3 , 1 , 0], [0 , 1, 2 , 3 , 1 , 100]])

In [16]:
values2.argmax()

11

In [17]:
values2.flat[11]

100

In [18]:
values2

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [19]:
values[0:6:1]

array([0, 1, 2, 3, 1, 0])

In [21]:
values[::]

array([0, 1, 2, 3, 1, 0])

In [22]:
values[0:6]

array([0, 1, 2, 3, 1, 0])

In [23]:
values[::-1]

array([0, 1, 3, 2, 1, 0])

In [24]:
values[0:6:-1]

array([], dtype=int64)

In [25]:
values[6:0:-1]

array([0, 1, 3, 2, 1])

In [26]:
values[0:-1:1]

array([0, 1, 2, 3, 1])

In [27]:
values[-2:-1:1]

array([1])

In [28]:
values[-2:0:1]

array([], dtype=int64)

In [29]:
values[-2:]

array([1, 0])

In [30]:
values2

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [31]:
values2[0:2]

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [32]:
values2[0:2, 0:2]

array([[0, 1],
       [0, 1]])

In [33]:
values2[0:2, 0:4]

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [34]:
values2[:-1, :-1]

array([[0, 1, 2, 3, 1]])

In [35]:
values2[:-1, :-1:-2]

array([], shape=(1, 0), dtype=int64)

In [36]:
values2[:-1, :-1:2]

array([[0, 2, 1]])

In [37]:
values2[:-1][:-1:2]

array([], shape=(0, 6), dtype=int64)

In [38]:
values2[0][:-1:2]

array([0, 2, 1])

In [39]:
values[:-1]

array([0, 1, 2, 3, 1])

In [40]:
values2[:-1]

array([[0, 1, 2, 3, 1, 0]])

In [41]:
values2[0]

array([0, 1, 2, 3, 1, 0])

In [42]:
values2[0][:-1:2]

array([0, 2, 1])

In [43]:
values2[:2]

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [44]:
values2[0][1]

1

In [45]:
values2[[0, 1]]

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [46]:
values2[0, 1]

1

In [47]:
print('values[0,1] faster than values[0][1]')

values[0,1] faster than values[0][1]


In [48]:
values2[[1,0]]

array([[  0,   1,   2,   3,   1, 100],
       [  0,   1,   2,   3,   1,   0]])

In [49]:
values2[[0, 1]]

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [50]:
values2

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [51]:
values2[[[1,0]]]

array([[  0,   1,   2,   3,   1, 100],
       [  0,   1,   2,   3,   1,   0]])

In [52]:
values2[[1,0,1]]

array([[  0,   1,   2,   3,   1, 100],
       [  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [53]:
values2[[1,1]]

array([[  0,   1,   2,   3,   1, 100],
       [  0,   1,   2,   3,   1, 100]])

In [54]:
values2

array([[  0,   1,   2,   3,   1,   0],
       [  0,   1,   2,   3,   1, 100]])

In [55]:
values2 + 1

array([[  1,   2,   3,   4,   2,   1],
       [  1,   2,   3,   4,   2, 101]])

In [56]:
values2 + np.array([[0], [1]])

array([[  0,   1,   2,   3,   1,   0],
       [  1,   2,   3,   4,   2, 101]])

In [57]:
values2 + np.array([0,1,3,4,5,6])

array([[  0,   2,   5,   7,   6,   6],
       [  0,   2,   5,   7,   6, 106]])

In [58]:
#################

In [59]:
def foo():
    return None

In [60]:
x = foo()

In [61]:
x == None

True

In [62]:
def foo2():
    return 1,2

In [63]:
a,b = foo2()

In [64]:
a

1

In [65]:
b

2

In [66]:
c = foo2()

In [67]:
c

(1, 2)

In [68]:
def foo3(a, b, c):
    return a+b+c

In [69]:
foo3(1,2,3)

6

In [70]:
foo3(*(1,2,3))

6

In [71]:
def foo4(*args):
    return sum(args[:3])
#     return args[0] + args[1] + args[2]

In [72]:
foo4(1,2,3,4,5)

6

In [73]:
def euler_step(u, f):
    return u + f(u)

In [81]:
from functools import lru_cache

In [82]:
def foo(x):
    prod = 1
    for i in range(1, x+1):
        prod *=i
    return prod

In [83]:
foo(3)

6

In [84]:
# decotator
lfoo = lru_cache()(foo)

In [85]:
@lru_cache()
def lfoo(x):
    prod = 1
    for i in range(1, x+1):
        prod *=i
    return prod

In [86]:
%%timeit
lfoo(10000)

104 ns ± 2.19 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [87]:
%%timeit
foo(10000)

23.4 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
